services:

  airflow_postgres:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5454:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  airflow_webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    depends_on:
      - airflow_postgres
    env_file:
      - .env.docker
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/src
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "8085:8080"
    command: webserver

  airflow_scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    depends_on:
      - airflow_webserver
    env_file:
      - .env.docker
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      PYTHONPATH: /opt/airflow/src
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: scheduler

  api:
    build: .
    container_name: api
    depends_on:
      - airflow_postgres
    env_file:
      - .env.docker
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DBNAME: ${PG_DBNAME}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  postgres_volume: